### ISSUE TITLE
undefined method 'placeholder' for Turnip::Steps::Module

### ISSUE THREAD

**Issue by denro** [jnicklas/turnip#62]
Hey!

looks like our placeholders aren't working with the 1.0.0 release.

we define them with:

```
steps_for :banners do
  step 'I fill in :banner_count :banner_type banner/banners' do |banner_count, banner_type|
    banner_count.times do |i|
      within "li.list:nth-of-type(#{i+1})" do
        fill_in 'Link', :with => "http://example.com"
        case banner_type
        when 'retina'
          attach_file "iPad Retina Banner Image", "spec/fixtures/files/valid_2x_banner.jpg"
        when 'standard'
          attach_file "iPad Banner Image", "spec/fixtures/files/valid_banner.jpg"
        end
      end
    end
  end

  placeholder :banner_count do
    match(/\d+/)      { |i| i.to_i }
    match(/another/)  { 2 }
    match(/a/)        { 1 }
  end
end
```

then when we load our steps we get the following error:

```

spec/acceptance/steps/banner_steps.rb:21:in `<module:Steps>': undefined method `placeholder' for Turnip::Steps:Module (NoMethodError)
    from spec/acceptance/steps/banner_steps.rb:1:in `<top (required)>'
    from /Users/denro/.rvm/gems/ruby-1.9.2-p320@serviceplus/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:245:in `load'
    from /Users/denro/.rvm/gems/ruby-1.9.2-p320@serviceplus/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:245:in `block in load'
    from /Users/denro/.rvm/gems/ruby-1.9.2-p320@serviceplus/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /Users/denro/.rvm/gems/ruby-1.9.2-p320@serviceplus/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:245:in `load'
    from /Users/denro/workspace/serviceplus/spec/support/turnip_steps_loader.rb:2:in `block in <top (required)>'
    from /Users/denro/workspace/serviceplus/spec/support/turnip_steps_loader.rb:2:in `glob'
    from /Users/denro/workspace/serviceplus/spec/support/turnip_steps_loader.rb:2:in `<top (required)>'
```

**Comment by tarky** [comment]
I also prefer the placeholder to be scoped in step or steps_for.

**Comment by nimaai** [comment]
> I also prefer the placeholder to be scoped in step or steps_for.

Me too.

**Comment by marian13** [comment]
> I also prefer the placeholder to be scoped in step or steps_for.

+1
